import type { NextPage } from 'next';
import Head from 'next/head';
import { Skeleton } from 'components/shared';
import styles from '../styles/Home.module.css';
import { ItemCard } from 'components/details';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shoe Shop</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* TODO: use css modules for styling: <main className={styles.main}> */}
      <div className="content home">
        <ItemCard>
          <Skeleton width={220} height={145} mb={16} />
          <Skeleton width={180} height={22} mb={8} />
          <Skeleton width={50} height={16} mb={8} />
          <Skeleton width={70} height={18} />
        </ItemCard>

        <ItemCard>
          <Skeleton width={220} height={145} mb={16} />
          <Skeleton width={180} height={22} mb={8} />
          <Skeleton width={50} height={16} mb={8} />
          <Skeleton width={70} height={18} />
        </ItemCard>

        <ItemCard>
          <Skeleton width={220} height={145} mb={16} />
          <Skeleton width={180} height={22} mb={8} />
          <Skeleton width={50} height={16} mb={8} />
          <Skeleton width={70} height={18} />
        </ItemCard>
      </div>
    </div>
  );
};

export default Home;
